'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CardMatching.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_error", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property done() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name5*0
        '''Name4*0
        '''Name3*0
        '''Name2*0
        '''Name1*0
        '''.
        '''</summary>
        Friend ReadOnly Property ehighscores() As String
            Get
                Return ResourceManager.GetString("ehighscores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name5*0
        '''Name4*0
        '''Name3*0
        '''Name2*0
        '''Name1*0
        '''.
        '''</summary>
        Friend ReadOnly Property hhighscores() As String
            Get
                Return ResourceManager.GetString("hhighscores", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property memory_card_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("memory-card-game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name5*0
        '''Name4*0
        '''Name3*0
        '''Name2*0
        '''Name1*0
        '''.
        '''</summary>
        Friend ReadOnly Property mhighscores() As String
            Get
                Return ResourceManager.GetString("mhighscores", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Users\Public\Documents\resources\ehighscores.txt
        '''C:\Users\Public\Documents\resources\mhighscores.txt
        '''C:\Users\Public\Documents\resources\hhighscores.txt
        '''C:\Users\Public\Documents\resources\ok.wav
        '''C:\Users\Public\Documents\resources\error.wav
        '''C:\Users\Public\Documents\resources\done.wav
        '''C:\Users\Public\Documents\resources\memory-card-game.png.
        '''</summary>
        Friend ReadOnly Property pathsoffiles() As String
            Get
                Return ResourceManager.GetString("pathsoffiles", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
